### PR TITLE
add support for serializable config

### PR DESCRIPTION
**Pull request by kswilliames**
This PR adds support for serializable cached config using PHP callables. Callables can be used to pass a callable class to the config array which is serialized to the cache, then called as a callable function on run-time.

Also incorporates @crezra's support for Laravel 9

For example:
```
// config/masked-dump.php
...
  'default' => [MaskedDump::class, 'define'],
...

// app/Support/MaskedDump.php

class MaskedDump
{
  public static function define()
  {
    return DumpSchema::define()->allTables();
  }
}
```

### CODE REVIEW

**Comment by kswilliames** [comment]
Closes #11

**Comment by mechelon** [comment]
Thanks!

**Comment by vpillinger-highwater** [comment]
@kswilliames This is a big necro but can you please update the website documentation to make this the preferred documented method? Breaking the serialization on the cache is a really big deal for any production application.

The main use-case of this package that I see is automating prod db exports, so the documentation is foot-gunning developers.

**Comment by kswilliames** [comment]
> @kswilliames This is a big necro but can you please update the website documentation to make this the preferred documented method? Breaking the serialization on the cache is a really big deal for any production application.
> 
> The main use-case of this package that I see is automating prod db exports, so the documentation is foot-gunning developers.

@vpillinger-highwater No worries for the necro. Sorry you had to experience the troubles, even after the fix! Although, it has been a while since I've worked with this plugin, Laravel or even PHP. Please review the new documentation PR and confirm that it's correct.

**Pull request merged**
