### PR TITLE
add support for Laravel 9 and bump testbench and phpunit versions

### PR DESCRIPTION
**Pull request by crezra**
Hi,

this PR adds support for Laravel 9
it also bumps versions for phpunit and testbench

Cheers

### CODE REVIEW

**Comment by JeppeSondergaard** [comment]
I would love to use this with laravel 9!

**Comment by faperreault** [comment]
+1

**Comment by harry-fakir** [comment]
has there been any progress on this? very keen

**Comment by jelleroorda** [comment]
+1, would love to see Laravel 9 support without having to use a fork.

**Comment by lasseeee** [comment]
Have you abandoned this package, @mpociot? It's of course totally alright, but would be nice to know wether we either should abandoned or fork it. Thanks anyhow for putting it out here for everyone to use :)

**Pull request merged**
